#!/usr/bin/env node
/**
 * Generates the release SBOM and the third-party license inventory, and fails
 * when a runtime dependency carries a copyleft license the project cannot ship.
 *
 *   node tooling/scripts/release-report.mjs [--check]
 *
 * Output: docs/security/sbom.json and docs/security/third-party-licenses.md
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const outputDir = join(repoRoot, "docs", "security");
const checkOnly = process.argv.includes("--check");

/** Licenses we refuse to ship in the runtime image. */
const DENIED = [/\bAGPL\b/i, /\bGPL-[23]\.0\b/i, /\bSSPL\b/i, /\bBUSL\b/i];

function pnpmJson(args) {
  try {
    const output = execFileSync("pnpm", args, {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return JSON.parse(output);
  } catch (error) {
    const stderr = error instanceof Error ? error.message : String(error);
    throw new Error(`pnpm ${args.join(" ")} failed: ${stderr}`);
  }
}

const all = pnpmJson(["licenses", "list", "--json"]);
const project = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8"));
const serverPackage = JSON.parse(
  readFileSync(join(repoRoot, "apps", "server", "package.json"), "utf8"),
);

let production = {};
try {
  production = pnpmJson(["licenses", "list", "--prod", "--json"]);
} catch {
  console.warn("warning: could not restrict the license list to production dependencies");
}

const components = [];
for (const [license, entries] of Object.entries(all)) {
  for (const entry of entries) {
    for (const version of entry.versions ?? []) {
      components.push({
        type: "library",
        name: entry.name,
        version,
        licenses: [{ license: { id: license } }],
        purl: `pkg:npm/${entry.name.replace("@", "%40")}@${version}`,
      });
    }
  }
}

components.sort((a, b) =>
  a.name === b.name ? a.version.localeCompare(b.version) : a.name.localeCompare(b.name),
);

const sbom = {
  bomFormat: "CycloneDX",
  specVersion: "1.5",
  version: 1,
  metadata: {
    component: {
      type: "application",
      name: project.name,
      version: project.version ?? "0.0.0",
      licenses: [{ license: { id: "Apache-2.0" } }],
    },
    // No wall-clock timestamp: the artefact must be byte-stable so CI can check
    // that the committed SBOM matches a fresh generation.
    tools: [{ vendor: "flowly", name: "release-report", version: "1" }],
  },
  components,
};

const byLicense = new Map();
for (const [license, entries] of Object.entries(all)) {
  const names = entries.map((entry) => `${entry.name}@${(entry.versions ?? []).join(", ")}`).sort();
  byLicense.set(license, names);
}

const lines = [
  "# Third-party licenses",
  "",
  "Generated by `pnpm release:report`. Do not edit by hand.",
  "",
  `Components: ${components.length}. Runtime dependencies of \`@flowly/server\`: ${
    Object.values(production).flat().length
  } packages.`,
  "",
  "## Runtime dependencies",
  "",
  ...[...Object.entries(production)]
    .sort(([a], [b]) => a.localeCompare(b))
    .flatMap(([license, entries]) => [
      `### ${license}`,
      "",
      ...entries.map((entry) => `- ${entry.name}@${(entry.versions ?? []).join(", ")}`).sort(),
      "",
    ]),
  "## Development and tooling dependencies",
  "",
  ...[...byLicense.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .flatMap(([license, names]) => [`### ${license}`, "", ...names.map((name) => `- ${name}`), ""]),
];

const violations = [];
for (const [license, entries] of Object.entries(production)) {
  if (DENIED.some((pattern) => pattern.test(license))) {
    violations.push(`${license}: ${entries.map((entry) => entry.name).join(", ")}`);
  }
}

const sbomPath = join(outputDir, "sbom.json");
const licensesPath = join(outputDir, "third-party-licenses.md");

if (checkOnly) {
  if (violations.length > 0) {
    console.error("Denied licenses in runtime dependencies:");
    for (const violation of violations) console.error(`  - ${violation}`);
    process.exit(1);
  }
  console.log(
    `License policy passed for ${Object.values(production).flat().length} runtime packages.`,
  );
  process.exit(0);
}

mkdirSync(outputDir, { recursive: true });
writeFileSync(sbomPath, `${JSON.stringify(sbom, null, 2)}\n`);
writeFileSync(licensesPath, `${lines.join("\n")}\n`);
console.log(
  `Wrote ${sbomPath} (${components.length} components) and ${licensesPath} for ${serverPackage.name}.`,
);

if (violations.length > 0) {
  console.error("Denied licenses in runtime dependencies:");
  for (const violation of violations) console.error(`  - ${violation}`);
  process.exit(1);
}
